#
# @file WORKSPACE
#
# @note WORKSPACE file for Bazel build
# 
# @author y-ksst / created on 2021/07/23
#
workspace( name="gwrt" )

new_local_repository(
    name = "thirdparty",
    path = "/media/yusuke/Moon/FromGitHub/stduuid",
    build_file = "thirdparty.BUILD",
)

# load( "@gwrt//External/OpenCV:cv_configure.bzl", "cv_autoconf" )
# cv_autoconf( name = "cv" )

# load( "@gwrt//External/GoogleTest:gtest_configure.bzl", "gtest_autoconf" )
# gtest_autoconf( name = "gtest" )
