#
# @file BUILD for Include
# 
# @author ykishishita / created on 2021/07/18
# 
#
load( "@gwrt//Main:gwrt.bzl", "gwrt_library" )

gwrt_library(
    name = "Include",
    hdrs = [ 
        "IntArray.h"
    ],
    srcs = [
        "IntArray.cpp"
    ],
    copts = [],
    deps = [
        
    ],
)
